import reflex as rx
from app.ui.states.legal_state import LegalState
from app.ui.components.legal_components import legal_page_layout, legal_section


def terms_and_conditions_page() -> rx.Component:
    return legal_page_layout(
        title=LegalState.content["terms_title"],
        last_updated=LegalState.last_updated,
        toc_items=LegalState.terms_toc,
        pdf_name="terms_and_conditions.pdf",
        children=[
            legal_section(
                "s1",
                LegalState.content["t_s1_title"],
                [rx.el.p(LegalState.content["t_s1_p1"])],
            ),
            legal_section(
                "s2",
                LegalState.content["t_s2_title"],
                [rx.el.p(LegalState.content["t_s2_p1"])],
            ),
            legal_section(
                "s3",
                LegalState.content["t_s3_title"],
                [rx.el.p(LegalState.content["t_s3_p1"])],
            ),
            legal_section(
                "s4",
                LegalState.content["t_s4_title"],
                [rx.el.p(LegalState.content["t_s4_p1"])],
            ),
            legal_section(
                "s5",
                LegalState.content["t_s5_title"],
                [rx.el.p(LegalState.content["t_s5_p1"])],
            ),
            legal_section(
                "s6",
                LegalState.content["t_s6_title"],
                [rx.el.p(LegalState.content["t_s6_p1"])],
            ),
            legal_section(
                "s7",
                LegalState.content["t_s7_title"],
                [rx.el.p(LegalState.content["t_s7_p1"])],
            ),
            legal_section(
                "s8",
                LegalState.content["t_s8_title"],
                [rx.el.p(LegalState.content["t_s8_p1"])],
            ),
            legal_section(
                "s9",
                LegalState.content["t_s9_title"],
                [rx.el.p(LegalState.content["t_s9_p1"])],
            ),
            legal_section(
                "s10",
                LegalState.content["t_s10_title"],
                [rx.el.p(LegalState.content["t_s10_p1"])],
            ),
            legal_section(
                "s11",
                LegalState.content["t_s11_title"],
                [
                    rx.el.p(
                        LegalState.content["t_s11_p1"],
                        rx.el.strong(LegalState.governing_law),
                        LegalState.content["t_s11_p2"],
                        rx.el.strong(LegalState.venue),
                        ".",
                    )
                ],
            ),
            legal_section(
                "s12",
                LegalState.content["t_s12_title"],
                [rx.el.p(LegalState.content["t_s12_p1"])],
            ),
            legal_section(
                "s13",
                LegalState.content["t_s13_title"],
                [rx.el.p(LegalState.content["t_s13_p1"])],
            ),
        ],
    )